### ISSUE TITLE
OrdinaryDiffEqSymplecticRK v1.2.0 does not work with OrdinaryDiffEqCore v1.6.0

### ISSUE THREAD

**Issue by ranocha** [SciML/OrdinaryDiffEq.jl#2600]
**Describe the bug 🐞**

In our downgrade CI tests in Trixi.jl, we get errors like

```
Failed to precompile OrdinaryDiffEq [1dea7af3-3e70-54e6-95c3-0bf5283fa5ed] to "/home/runner/.julia/compiled/v1.10/OrdinaryDiffEq/jl_1nC69q".
ERROR: LoadError: UndefVarError: `default_linear_interpolation` not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:31
 [2] top-level scope
   @ ~/.julia/packages/OrdinaryDiffEqSymplecticRK/8SXKX/src/algorithms.jl:47
 [3] include(mod::Module, _path::String)
   @ Base ./Base.jl:495
 [4] include(x::String)
   @ OrdinaryDiffEqSymplecticRK ~/.julia/packages/OrdinaryDiffEqSymplecticRK/8SXKX/src/OrdinaryDiffEqSymplecticRK.jl:1
```

see https://github.com/trixi-framework/Trixi.jl/actions/runs/13289523231/job/37106464367?pr=2281#step:8:1098

**Expected behavior**

We can install OrdinaryDiffEq.jl without issues.

**Minimal Reproducible Example 👇**

Without MRE, we would only be able to help you to a limited extent, and attention to the issue would be limited. to know more about MRE refer to [wikipedia](https://en.wikipedia.org/wiki/Minimal_reproducible_example) and [stackoverflow](https://stackoverflow.com/help/minimal-reproducible-example).

```julia
julia> import Pkg; Pkg.activate(temp = true)

julia> Pkg.add([
           Pkg.PackageSpec(name = "OrdinaryDiffEqSymplecticRK", version = v"1.2.0"),
           Pkg.PackageSpec(name = "OrdinaryDiffEqCore", version = v"1.6.0"),
           Pkg.PackageSpec(name = "OrdinaryDiffEq", version = v"6.88.1")
       ])
```

**Error & Stacktrace ⚠️**

See above

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
julia> Pkg.status()
Status `.../Project.toml`
⌃ [1dea7af3] OrdinaryDiffEq v6.88.1
⌃ [bbf590c4] OrdinaryDiffEqCore v1.6.0
  [fa646aed] OrdinaryDiffEqSymplecticRK v1.2.0
Info Packages marked with ⌃ have new versions available and may be upgradable.
```

  - Output of `using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)`

```julia
julia> Pkg.status(; mode = Pkg.PKGMODE_MANIFEST)
Status `.../Manifest.toml`
  [47edcb42] ADTypes v1.13.0
  [7d9f7c33] Accessors v0.1.41
  [79e6a3ab] Adapt v4.1.1
  [ec485272] ArnoldiMethod v0.4.0
  [4fba245c] ArrayInterface v7.18.0
  [4c555306] ArrayLayouts v1.11.0
  [62783981] BitTwiddlingConvenienceFunctions v0.1.6
  [2a0fbf3d] CPUSummary v0.2.6
  [d360d2e6] ChainRulesCore v1.25.1
  [fb6a15b2] CloseOpenIntervals v0.1.13
  [38540f10] CommonSolve v0.2.4
  [bbf7d656] CommonSubexpressions v0.3.1
  [f70d9fcc] CommonWorldInvalidations v1.0.0
  [34da2185] Compat v4.16.0
  [a33af91c] CompositionsBase v0.1.2
  [2569d6c7] ConcreteStructs v0.2.3
  [187b0558] ConstructionBase v1.5.8
  [adafc99b] CpuId v0.3.1
  [9a962f9c] DataAPI v1.16.0
  [864edb3b] DataStructures v0.18.20
  [e2d170a0] DataValueInterfaces v1.0.0
  [2b5f629d] DiffEqBase v6.162.2
  [163ba53b] DiffResults v1.1.0
  [b552c78f] DiffRules v1.15.1
  [a0c0ee7d] DifferentiationInterface v0.6.40
  [ffbed154] DocStringExtensions v0.9.3
  [4e289a0a] EnumX v1.0.4
  [f151be2c] EnzymeCore v0.8.8
  [d4d017d3] ExponentialUtilities v1.27.0
  [e2ba6199] ExprTools v0.1.10
⌅ [6b7a57c9] Expronicon v0.8.5
  [7034ab61] FastBroadcast v0.3.5
  [9aa1b823] FastClosures v0.3.2
  [29a986be] FastLapackInterface v2.0.4
  [a4df4552] FastPower v1.1.1
  [1a297f60] FillArrays v1.13.0
  [6a86dc24] FiniteDiff v2.27.0
  [f6369f11] ForwardDiff v0.10.38
  [069b7b12] FunctionWrappers v1.1.3
  [77dc65aa] FunctionWrappersWrappers v0.1.3
  [46192b85] GPUArraysCore v0.2.0
  [c145ed77] GenericSchur v0.5.4
  [86223c79] Graphs v1.12.0
  [3e5b6fbb] HostCPUFeatures v0.1.17
  [615f187c] IfElse v0.1.1
  [d25df0c9] Inflate v0.1.5
  [3587e190] InverseFunctions v0.1.17
  [92d709cd] IrrationalConstants v0.2.4
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.7.0
  [ef3ab10e] KLU v0.6.0
  [ba0b0d4f] Krylov v0.9.9
  [10f19ff3] LayoutPointers v0.1.17
  [5078a376] LazyArrays v2.6.0
  [87fe0de2] LineSearch v0.1.4
  [d3d80556] LineSearches v7.3.0
⌅ [7ed4a6bd] LinearSolve v2.39.0
  [2ab3a3ac] LogExpFunctions v0.3.29
  [bdcacae8] LoopVectorization v0.12.171
  [d8e11817] MLStyle v0.4.17
  [1914dd2f] MacroTools v0.5.15
  [d125e4d3] ManualMemory v0.1.8
  [bb5d69b7] MaybeInplace v0.1.4
  [46d2c3a1] MuladdMacro v0.2.4
  [d41bc354] NLSolversBase v7.8.3
  [77ba4419] NaNMath v1.1.2
⌅ [8913a72c] NonlinearSolve v3.15.1
  [6fe1bfb0] OffsetArrays v1.15.0
  [bac558e1] OrderedCollections v1.8.0
⌃ [1dea7af3] OrdinaryDiffEq v6.88.1
  [89bda076] OrdinaryDiffEqAdamsBashforthMoulton v1.2.0
⌃ [6ad6398a] OrdinaryDiffEqBDF v1.1.2
⌃ [bbf590c4] OrdinaryDiffEqCore v1.6.0
⌃ [50262376] OrdinaryDiffEqDefault v1.1.0
⌃ [4302a76b] OrdinaryDiffEqDifferentiation v1.2.0
  [9286f039] OrdinaryDiffEqExplicitRK v1.1.0
⌃ [e0540318] OrdinaryDiffEqExponentialRK v1.1.0
⌃ [becaefa8] OrdinaryDiffEqExtrapolation v1.2.1
⌃ [5960d6e9] OrdinaryDiffEqFIRK v1.5.0
  [101fe9f7] OrdinaryDiffEqFeagin v1.1.0
  [d3585ca7] OrdinaryDiffEqFunctionMap v1.1.1
  [d28bc4f8] OrdinaryDiffEqHighOrderRK v1.1.0
⌃ [9f002381] OrdinaryDiffEqIMEXMultistep v1.1.0
  [521117fe] OrdinaryDiffEqLinear v1.1.0
  [1344f307] OrdinaryDiffEqLowOrderRK v1.2.0
  [b0944070] OrdinaryDiffEqLowStorageRK v1.2.1
⌃ [127b3ac7] OrdinaryDiffEqNonlinearSolve v1.3.0
  [c9986a66] OrdinaryDiffEqNordsieck v1.1.0
⌃ [5dd0a6cf] OrdinaryDiffEqPDIRK v1.1.0
  [5b33eab2] OrdinaryDiffEqPRK v1.1.0
  [04162be5] OrdinaryDiffEqQPRK v1.1.0
  [af6ede74] OrdinaryDiffEqRKN v1.1.0
⌃ [43230ef6] OrdinaryDiffEqRosenbrock v1.3.1
⌃ [2d112036] OrdinaryDiffEqSDIRK v1.1.0
  [669c94d9] OrdinaryDiffEqSSPRK v1.2.0
⌃ [e3e12d00] OrdinaryDiffEqStabilizedIRK v1.1.0
  [358294b1] OrdinaryDiffEqStabilizedRK v1.1.0
  [fa646aed] OrdinaryDiffEqSymplecticRK v1.2.0
  [b1df2697] OrdinaryDiffEqTsit5 v1.1.0
  [79d7bb75] OrdinaryDiffEqVerner v1.1.1
  [65ce6f38] PackageExtensionCompat v1.0.2
  [d96e819e] Parameters v0.12.3
  [f517fe37] Polyester v0.7.16
  [1d0040c9] PolyesterWeave v0.2.2
  [d236fae5] PreallocationTools v0.4.24
  [aea7be01] PrecompileTools v1.2.1
  [21216c6a] Preferences v1.4.3
  [3cdcf5f2] RecipesBase v1.3.4
  [731186ca] RecursiveArrayTools v3.29.0
  [f2c3362d] RecursiveFactorization v0.2.23
  [189a3867] Reexport v1.2.2
  [ae029012] Requires v1.3.0
  [7e49a35a] RuntimeGeneratedFunctions v0.5.13
  [94e857df] SIMDTypes v0.1.0
  [476501e8] SLEEFPirates v0.6.43
  [0bca4576] SciMLBase v2.74.0
  [19f34311] SciMLJacobianOperators v0.1.1
  [c0aeaf25] SciMLOperators v0.3.12
  [53ae85a6] SciMLStructures v1.6.1
  [efcf1570] Setfield v1.1.1
⌅ [727e6d20] SimpleNonlinearSolve v1.12.3
  [699a6c99] SimpleTraits v0.9.4
  [ce78b400] SimpleUnPack v1.1.0
  [9f842d2f] SparseConnectivityTracer v0.6.12
  [47a9eef4] SparseDiffTools v2.23.1
  [0a514795] SparseMatrixColorings v0.4.13
  [e56a9233] Sparspak v0.3.9
  [276daf66] SpecialFunctions v2.5.0
  [aedffcd0] Static v1.1.1
  [0d7ed370] StaticArrayInterface v1.8.0
  [90137ffa] StaticArrays v1.9.12
  [1e83bf80] StaticArraysCore v1.4.3
  [7792a7ef] StrideArraysCore v0.5.7
  [2efcf032] SymbolicIndexingInterface v0.3.37
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.12.0
  [8290d209] ThreadingUtilities v0.5.2
  [a759f4b9] TimerOutputs v0.5.26
  [d5829a12] TriangularSolve v0.2.1
  [781d530d] TruncatedStacktraces v1.4.0
  [3a884ed6] UnPack v1.0.2
  [3d5dd08c] VectorizationBase v0.21.71
  [19fa3120] VertexSafeGraphs v0.2.0
  [1d5cc7b8] IntelOpenMP_jll v2025.0.4+0
  [856f044c] MKL_jll v2025.0.1+1
  [efe28fd5] OpenSpecFun_jll v0.5.6+0
  [1317d2d5] oneTBB_jll v2021.12.0+0
  [0dad84c5] ArgTools v1.1.1
  [56f22d72] Artifacts
  [2a0f44e3] Base64
  [ade2ca70] Dates
  [8ba89e20] Distributed
  [f43a241f] Downloads v1.6.0
  [7b1f6079] FileWatching
  [9fa8497b] Future
  [b77e0a4c] InteractiveUtils
  [4af54fe1] LazyArtifacts
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [d6f4376e] Markdown
  [a63ad114] Mmap
  [ca575930] NetworkOptions v1.2.0
  [44cfe95a] Pkg v1.10.0
  [de0858da] Printf
  [3fa0cd96] REPL
  [9a3f8284] Random
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization
  [1a1011a3] SharedArrays
  [6462fe0b] Sockets
  [2f01184e] SparseArrays v1.10.0
  [10745b16] Statistics v1.10.0
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test
  [cf7118a7] UUIDs
  [4ec0a83e] Unicode
  [e66e0078] CompilerSupportLibraries_jll v1.1.1+0
  [deac9b47] LibCURL_jll v8.4.0+0
  [e37daf67] LibGit2_jll v1.6.4+0
  [29816b5a] LibSSH2_jll v1.11.0+1
  [c8ffd9c3] MbedTLS_jll v2.28.2+1
  [14a3606d] MozillaCACerts_jll v2023.1.10
  [4536629a] OpenBLAS_jll v0.3.23+4
  [05823500] OpenLibm_jll v0.8.1+2
  [bea87d4a] SuiteSparse_jll v7.2.1+1
  [83775a58] Zlib_jll v1.2.13+1
  [8e850b90] libblastrampoline_jll v5.11.0+0
  [8e850ede] nghttp2_jll v1.52.0+1
  [3f19e933] p7zip_jll v17.4.0+2
```

**Additional context**

Everything worked as it should with OrdinaryDiffEqSymplecticRK v1.1.0

**Comment by ChrisRackauckas** [comment]
I did a new release that should now work with the downgrade CI. Though, we cannot really roll out downgrade CI until the version with the fixed resolver is completed.

**Comment by JoshuaLampert** [comment]
Thanks! Do I understand correctly that we now have to explicitly depend on `OrdinaryDiffEqSymplecticRK = 1.3.0` in our Project.toml to fix our Downgrade job even though we are not even using anything from OrdinaryDiffEqSymplecticRK.jl?
(I know that an alternative fix would be to only depend on the OrdinaryDiffEq.jl subpackages that we actually need and we are working on that (https://github.com/trixi-framework/Trixi.jl/pull/2266), but this will need some time and we would like to fix our CI already before that.)

**Comment by ranocha** [comment]
Thanks. However, it still does not work for us. We need to invest more time into the Downgrade actions in Trixi.jl since we are currently restricted to DiffEqBase.jl v6.154 and

```julia
julia> import Pkg; Pkg.activate(temp = true)

julia> Pkg.add([
           #Pkg.PackageSpec(name = "OrdinaryDiffEqSymplecticRK", version = v"1.2.0"),
           #Pkg.PackageSpec(name = "OrdinaryDiffEqCore", version = v"1.6.0"),
           Pkg.PackageSpec(name = "DiffEqBase", version = v"6.154")
           Pkg.PackageSpec(name = "OrdinaryDiffEq", version = v"6.88.1")
       ])
```

allows us to get at most v1.2.0 of OrdinaryDiffEqSymplecticRK.jl...

**Comment by ChrisRackauckas** [comment]
I'm not sure we can do anything there other than if we change the General registry, which is why a bump in the package version is usually what's recommended.

**Comment by ranocha** [comment]
Okay, we'll go that route. Thanks
